seed_everything: true

ckpt_path: null

data:
  class_path: "varautoenc.MNISTDataModule"
  init_args:
    data_dir: "run/data"
    binarize_threshold: 0.5
    batch_size: 32
    num_workers: 0

model:
  class_path: "varautoenc.ConvVAE"
  init_args:
    num_channels: [1, 16, 32]
    num_features: [1568, 512, 128]
    reshape: [32, 7, 7]
    kernel_size: 3
    pooling: 2
    upsample_mode: "conv_transpose"
    batchnorm: true
    activation: "elu"
    last_activation: null
    drop_rate: null
    pool_last: true
    double_conv: true
    num_samples: 1
    likelihood_type: "Bernoulli"
    sigma: null
    per_channel: false
    lr: 0.001

trainer:
  accelerator: "cpu"
  max_epochs: 100
  log_every_n_steps: 100
  logger:
    class_path: "lightning.pytorch.loggers.TensorBoardLogger"
    init_args:
      save_dir: "run/"
      name: "mnist_conv"
      version: null
  callbacks:
    - class_path: "lightning.pytorch.callbacks.ModelCheckpoint"
      init_args:
        filename: "best"
        monitor: "val_loss"
        mode: "min"
        save_top_k: 1
    - class_path: "lightning.pytorch.callbacks.ModelCheckpoint"
      init_args:
        filename: "{epoch}_{val_loss:.2f}"
        save_top_k: -1
        every_n_epochs: 1
        save_last: true

